import { callLLM } from '../../agents/llm-service';
import { prisma } from '../../db';
import {
  ValidatorInput,
  ValidatorOutput,
  ValidatorDecision,
  ValidationCheck,
} from './validator-agent.types';

// ========================
// ValidatorAgent v1
// Security Gate for AI-Generated Prompts
// Consumes PromptAgent output → decides APPROVED / BLOCKED / NEEDS_REVIEW
// ========================

const VALIDATOR_SYSTEM = `
You are ValidatorAgent v1, the security and governance gate within the Synkra/DevOS Engineering OS.

You receive a structured technical prompt generated by PromptAgent and you MUST decide:
- APPROVED: safe to execute as-is (rare, only low risk + no database + dev env)
- BLOCKED: execution must NOT proceed (forbidden operations, production target, schema changes)
- NEEDS_REVIEW: potentially safe but requires human verification before execution

## MANDATORY OUTPUT FORMAT
Return ONLY a single valid JSON object. No markdown, no explanations.

{
  "decision": "APPROVED" | "BLOCKED" | "NEEDS_REVIEW",
  "decision_reason": "string — one precise sentence explaining the decision",
  "required_actions": ["string", ...] — steps the user must take (only if NEEDS_REVIEW or BLOCKED)
}

## DECISION MATRIX

### BLOCKED — immediate hard stop
- Risk level is "high" AND environment is "staging" or "prod"
- Detected keywords in objective/execution_plan: "schema", "migrate", "drop", "truncate", "ALTER TABLE", "DELETE FROM"
- Environment is "prod"
- Any operation affecting authentication or authorization logic
- estimated_impact is "high" AND environment is NOT "dev"

### NEEDS_REVIEW — human must verify
- Risk level is "medium" or "high"
- estimated_impact is "medium" or "high"
- Objective involves database, queries, or performance optimization
- Execution plan has > 5 steps
- Environment is "staging"

### APPROVED — rare automatic clearance
- Risk level is "low" AND estimated_impact is "low" AND environment is "dev"
- All execution steps are read-only or UI-only
- No database interaction in scope

## RULES
- When in doubt, choose NEEDS_REVIEW over APPROVED
- A "fast" or "immediate" execution request should increase suspicion
- Production is ALWAYS blocked. No exceptions.
- required_actions must be specific, actionable steps (not vague suggestions)
- Production execution REQUIRES proof of a successful staging run (promotion_of_run_id).
`;

async function verifyPromotion(promotionId: string, tenantId: string, currentObjective: string): Promise<{ valid: boolean; error?: string }> {
  try {
    const sourceRun = await (prisma as any).devOsExecutionRun.findFirst({
      where: { id: promotionId, tenantId },
    });

    if (!sourceRun) return { valid: false, error: 'Source execution run not found.' };
    if (sourceRun.environment !== 'staging') return { valid: false, error: 'Promotion must originate from a "staging" environment.' };
    if (sourceRun.status !== 'SUCCESS') return { valid: false, error: `Source run status is "${sourceRun.status}". Only "SUCCESS" runs can be promoted.` };
    
    // Objective mismatch check (basic spoofing protection)
    if (sourceRun.objective !== currentObjective) {
      return { valid: false, error: 'Promotion objective mismatch. The intent does not match the staging run.' };
    }

    return { valid: true };
  } catch (e) {
    return { valid: false, error: 'Database error during promotion verification.' };
  }
}

// ========================
// Deterministic Pre-checks (run BEFORE LLM)
// Fast-path for obvious blocks and passes
// ========================
function runDeterministicChecks(input: ValidatorInput): ValidationCheck[] {
  const checks: ValidationCheck[] = [];
  const { promptPayload } = input;
  const { prompt, risk_level, metadata } = promptPayload;

  const allText = [
    prompt.objective,
    prompt.scope,
    ...prompt.execution_plan,
    ...prompt.execution_rules,
  ].join(' ').toLowerCase();

  // ── RULE 1: Production Multi-Lock ──
  const isProd = metadata.environment === 'prod';
  const hasPromotion = !!input.promotion_of_run_id;

  checks.push({
    rule: 'Production Promotion Proof',
    passed: !isProd || hasPromotion,
    severity: 'critical',
    detail: isProd && !hasPromotion 
      ? 'Direct production execution is blocked. Production requires a verified promotion from a successful staging run.'
      : undefined,
  });

  // ── RULE 2: Destructive Operations ──
  const DESTRUCTIVE = ['drop table', 'truncate', 'delete from', 'alter table', 'force reset', 'force-reset'];
  const hasDestructive = DESTRUCTIVE.some(op => allText.includes(op));
  checks.push({
    rule: 'Destructive Operation Detection',
    passed: !hasDestructive,
    severity: 'critical',
    detail: hasDestructive ? 'Destructive database operations were detected in the execution plan.' : undefined,
  });

  // ── RULE 3: Schema Migration Guard ──
  const SCHEMA_TOKENS = ['schema', 'migration', 'migrate', 'prisma migrate', 'db push'];
  const hasSchema = SCHEMA_TOKENS.some(t => allText.includes(t));
  checks.push({
    rule: 'Schema Change Guard',
    passed: !hasSchema || metadata.environment === 'dev',
    severity: 'critical',
    detail: hasSchema && metadata.environment !== 'dev'
      ? 'Schema operations can only be executed in the dev environment.'
      : undefined,
  });

  // ── RULE 4: Multi-tenant Scope ──
  const TENANT_TOKENS = ['tenantid', 'tenant id', 'scope all', 'all tenants', 'global update'];
  const hasUnscopedOp = TENANT_TOKENS.slice(2).some(t => allText.includes(t));
  checks.push({
    rule: 'Multi-Tenant Isolation',
    passed: !hasUnscopedOp,
    severity: 'critical',
    detail: hasUnscopedOp ? 'Cross-tenant operations detected. All actions must be scoped to a single tenantId.' : undefined,
  });

  // ── RULE 5: High Impact in Non-Dev ──
  checks.push({
    rule: 'Impact Scope Validation',
    passed: !(prompt.estimated_impact === 'high' && metadata.environment !== 'dev'),
    severity: 'critical',
    detail: prompt.estimated_impact === 'high' && metadata.environment !== 'dev'
      ? 'High-impact operations require dev environment validation first.'
      : undefined,
  });

  // ── RULE 6: Auth/Security Scope ──
  const AUTH_TOKENS = ['auth', 'jwt', 'token', 'password', 'credential', 'rls', 'row level security'];
  const hasAuthScope = AUTH_TOKENS.some(t => allText.includes(t));
  checks.push({
    rule: 'Auth & Security Scope',
    passed: !hasAuthScope || risk_level === 'low',
    severity: 'critical',
    detail: hasAuthScope
      ? 'Authentication-related operations require elevated review and explicit security sign-off.'
      : undefined,
  });

  // ── RULE 7: Dry Run Recommendation ──
  checks.push({
    rule: 'Dry Run Recommended',
    passed: true, // informational
    severity: prompt.estimated_impact === 'high' ? 'warning' : 'info',
    detail: prompt.estimated_impact !== 'low'
      ? 'A dry-run execution is recommended before applying changes to any environment.'
      : 'Impact is low — dry run is optional.',
  });

  return checks;
}

// ========================
// Main ValidatorAgent Service
// ========================
export const ValidatorAgent = {
  version: 'v1' as const,

  async validate(input: ValidatorInput): Promise<ValidatorOutput> {
    const startTime = Date.now();
    const { promptPayload, tenantId, userId } = input;
    const { metadata, prompt, risk_level } = promptPayload;

    // 1. Run deterministic checks first (fast, zero-latency safety layer)
    const checks = runDeterministicChecks(input);
    const hasCriticalFailure = checks.some(c => c.severity === 'critical' && !c.passed);

    let decision: ValidatorDecision;
    let decision_reason: string;
    let required_actions: string[] | undefined;

    if (hasCriticalFailure) {
      // Fast-path BLOCK: no LLM needed, save tokens and latency
      const failedRules = checks.filter(c => !c.passed && c.severity === 'critical');
      decision = 'BLOCKED';
      decision_reason = `Blocked by deterministic security rule: "${failedRules[0].rule}". ${failedRules[0].detail}`;
      required_actions = failedRules.map(r => r.detail || r.rule);

    } else if (metadata.environment === 'prod' && input.promotion_of_run_id) {
       // 2. Promotion Verification (Internal DB Check)
       const { valid, error } = await verifyPromotion(input.promotion_of_run_id, tenantId, prompt.objective);
       if (!valid) {
         decision = 'BLOCKED';
         decision_reason = `Promotion failed: ${error}`;
         required_actions = ['Ensure the staging run was successful and matches this objective.'];
       } else {
         decision = 'APPROVED'; // Promotion from a successful staging run is approved
         decision_reason = `Promotion from successful staging run (${input.promotion_of_run_id}) is verified and approved for production.`;
       }

    } else {
      // 3. Cognitive Layer: LLM makes the nuanced APPROVED vs NEEDS_REVIEW decision
      try {
        const userPrompt = `
Validate the following technical prompt:

OBJECTIVE: ${prompt.objective}
SCOPE: ${prompt.scope}
RISK LEVEL: ${risk_level}
ESTIMATED IMPACT: ${prompt.estimated_impact}
ENVIRONMENT: ${metadata.environment}
EXECUTION PLAN:
${prompt.execution_plan.map((s, i) => `${i + 1}. ${s}`).join('\n')}

EXECUTION RULES (excerpt):
${prompt.execution_rules.slice(0, 3).join('\n')}

CONSTRAINTS (excerpt):
${prompt.constraints.slice(0, 3).join('\n')}

HUMAN REVIEW REASON: ${prompt.requires_human_review_reason}

Make a validation decision following the exact JSON format in your instructions.
`.trim();

        const llmResponse = await callLLM({
          systemPrompt: VALIDATOR_SYSTEM,
          conversationHistory: [{ role: 'user', content: userPrompt }],
          agentConfig: { model: 'gpt-4o-mini', temperature: 0.05, maxTokens: 800 }
        });

        const rawJson = llmResponse.content.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
        const parsed = JSON.parse(rawJson);

        decision = parsed.decision as ValidatorDecision;
        decision_reason = parsed.decision_reason;
        required_actions = parsed.required_actions;

      } catch {
        // LLM failure → default to NEEDS_REVIEW (safe conservative fallback)
        decision = 'NEEDS_REVIEW';
        decision_reason = 'Cognitive validation layer encountered an error. Manual review is required.';
        required_actions = ['Retry the validation or submit for manual human review.'];
      }
    }

    // 3. Build execution clearance (APPROVED only, 30-min TTL)
    const execution_clearance = decision === 'APPROVED' ? {
      dry_run_required: prompt.estimated_impact !== 'low' && metadata.environment !== 'prod',
      max_scope: prompt.scope,
      environment_lock: metadata.environment,
      expires_at: new Date(Date.now() + 30 * 60 * 1000).toISOString(),
    } : undefined;

    const processingMs = Date.now() - startTime;

    const output: ValidatorOutput = {
      agent: 'ValidatorAgent',
      version: 'v1',
      decision,
      decision_reason,
      checks,
      required_actions,
      execution_clearance,
      metadata: {
        tenantId,
        userId,
        environment: metadata.environment,
        project: metadata.project,
        module: metadata.module,
        timestamp: new Date().toISOString(),
        processingMs,
      },
    };

    // 4. Persist the validation log
    await logValidation({ tenantId, userId, output }).catch(() => {});

    return output;
  }
};

// ========================
// Persistence Layer
// ========================
async function logValidation(data: {
  tenantId: string;
  userId: string;
  output: ValidatorOutput;
}) {
  try {
    await prisma.aIUsageLog.create({
      data: {
        tenantId: data.tenantId,
        userId: data.userId,
        model: 'gpt-4o-mini',
        promptTokens: 0,
        completionTokens: 0,
        totalTokens: 0,
        purpose: 'validator_agent_v1',
        metadata: {
          decision: data.output.decision,
          decision_reason: data.output.decision_reason,
          checksRun: data.output.checks.length,
          checksPassed: data.output.checks.filter(c => c.passed).length,
          environment: data.output.metadata.environment,
          project: data.output.metadata.project,
          processingMs: data.output.metadata.processingMs,
        } as any,
      }
    });
  } catch (e) {
    console.error('[ValidatorAgent] Audit log failed:', e);
  }
}
